import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:csv/csv.dart';
import '../core/services/gemini_service.dart';
import '../models/aptitude_problem_model.dart';
import '../repositories/aptitude_repository.dart';
import 'aptitude_provider.dart';
import 'resume_provider.dart';

class AdminImporterState {
  final bool isLoading;
  final String? statusMessage;
  final int totalQuestionCount;
  final List<AptitudeProblemModel> recentQuestions;

  AdminImporterState({
    this.isLoading = false,
    this.statusMessage,
    this.totalQuestionCount = 0,
    this.recentQuestions = const [],
  });

  AdminImporterState copyWith({
    bool? isLoading,
    String? statusMessage,
    int? totalQuestionCount,
    List<AptitudeProblemModel>? recentQuestions,
  }) {
    return AdminImporterState(
      isLoading: isLoading ?? this.isLoading,
      statusMessage: statusMessage,
      totalQuestionCount: totalQuestionCount ?? this.totalQuestionCount,
      recentQuestions: recentQuestions ?? this.recentQuestions,
    );
  }
}

class AdminImporterNotifier extends Notifier<AdminImporterState> {
  @override
  AdminImporterState build() {
    Future.microtask(() => refreshStats());
    return AdminImporterState();
  }

  /// Refreshes question count and recent questions list.
  Future<void> refreshStats() async {
    final repo = ref.read(aptitudeRepositoryProvider);
    final count = await repo.getQuestionCount();
    state = state.copyWith(totalQuestionCount: count);
  }

  /// Saves a single question manually (Tab 1).
  Future<bool> saveManualQuestion(AptitudeProblemModel question) async {
    state = state.copyWith(isLoading: true, statusMessage: "Saving question to Firestore...");
    try {
      final repo = ref.read(aptitudeRepositoryProvider);
      await repo.saveQuestion(question);
      await refreshStats();
      state = state.copyWith(
        isLoading: false,
        statusMessage: "Success: Question saved to aptitude_problems!",
      );
      return true;
    } catch (e) {
      state = state.copyWith(isLoading: false, statusMessage: "Error saving question: $e");
      return false;
    }
  }

  /// Generates answers & explanations with AI for bulk text (Tab 2).
  Future<List<AptitudeProblemModel>> generateAiAnswersForRawText({
    required String rawText,
  }) async {
    state = state.copyWith(isLoading: true, statusMessage: "Sending questions to Gemini AI...");
    try {
      final gemini = ref.read(geminiServiceProvider);
      final aiResults = await gemini.generateAptitudeAnswersBatch(rawText);

      final blocks = rawText.split(RegExp(r'\n\s*\n'));
      final generatedList = <AptitudeProblemModel>[];

      for (int i = 0; i < blocks.length; i++) {
        final block = blocks[i].trim();
        if (block.isEmpty) continue;

        final lines = block.split('\n').map((l) => l.trim()).toList();
        String qText = "";
        List<String> options = [];
        String category = "quantitative";
        int year = 2024;
        String company = "TCS";

        for (final line in lines) {
          if (line.toLowerCase().startsWith('q:')) {
            qText = line.substring(2).trim();
          } else if (line.toLowerCase().startsWith('a)')) {
            options.add(line.substring(2).trim());
          } else if (line.toLowerCase().startsWith('b)')) {
            options.add(line.substring(2).trim());
          } else if (line.toLowerCase().startsWith('c)')) {
            options.add(line.substring(2).trim());
          } else if (line.toLowerCase().startsWith('d)')) {
            options.add(line.substring(2).trim());
          } else if (line.toLowerCase().startsWith('category:')) {
            category = line.substring(9).trim().toLowerCase();
          } else if (line.toLowerCase().startsWith('year:')) {
            year = int.tryParse(line.substring(5).trim()) ?? 2024;
          } else if (line.toLowerCase().startsWith('company:')) {
            company = line.substring(8).trim();
          } else if (qText.isEmpty) {
            qText = line;
          }
        }

        while (options.length < 4) {
          options.add("Option ${options.length + 1}");
        }

        final aiData = i < aiResults.length ? aiResults[i] : {};
        final correctIdx = (aiData['correctOptionIndex'] as num?)?.toInt() ?? 0;
        final explanation = aiData['explanation']?.toString() ?? "Generated by Gemini AI.";

        generatedList.add(AptitudeProblemModel(
          id: 'ap_ai_${DateTime.now().millisecondsSinceEpoch}_$i',
          category: category,
          year: year,
          company: company,
          questionText: qText.isNotEmpty ? qText : "Question ${i + 1}",
          options: options.take(4).toList(),
          correctOptionIndex: correctIdx,
          explanation: explanation,
          difficulty: 'medium',
        ));
      }

      state = state.copyWith(
        isLoading: false,
        statusMessage: "AI generated answers for ${generatedList.length} questions!",
      );
      return generatedList;
    } catch (e) {
      state = state.copyWith(isLoading: false, statusMessage: "Error generating with AI: $e");
      return [];
    }
  }

  /// Batch saves AI generated questions.
  Future<bool> saveQuestionsBatch(List<AptitudeProblemModel> questions) async {
    state = state.copyWith(isLoading: true, statusMessage: "Saving ${questions.length} questions to Firestore...");
    try {
      final repo = ref.read(aptitudeRepositoryProvider);
      await repo.saveQuestionsBatch(questions);
      await refreshStats();
      state = state.copyWith(
        isLoading: false,
        statusMessage: "Successfully imported ${questions.length} questions!",
      );
      return true;
    } catch (e) {
      state = state.copyWith(isLoading: false, statusMessage: "Error importing batch: $e");
      return false;
    }
  }

  /// Parses CSV string and converts to question models (Tab 3).
  List<AptitudeProblemModel> parseCsvString(String csvContent) {
    final fields = const CsvToListConverter().convert(csvContent, eol: '\n');
    if (fields.isEmpty) return [];

    final list = <AptitudeProblemModel>[];
    final startIdx = (fields.first.isNotEmpty && fields.first.first.toString().toLowerCase().contains('category')) ? 1 : 0;

    for (int i = startIdx; i < fields.length; i++) {
      final row = fields[i];
      if (row.length < 9) continue;

      final category = row[0].toString().trim().toLowerCase();
      final year = int.tryParse(row[1].toString().trim()) ?? 2024;
      final company = row[2].toString().trim();
      final questionText = row[3].toString().trim();
      final optionA = row[4].toString().trim();
      final optionB = row[5].toString().trim();
      final optionC = row[6].toString().trim();
      final optionD = row[7].toString().trim();
      final correctOptStr = row[8].toString().trim().toUpperCase();

      int correctIdx = 0;
      if (correctOptStr == 'B' || correctOptStr == '1') correctIdx = 1;
      if (correctOptStr == 'C' || correctOptStr == '2') correctIdx = 2;
      if (correctOptStr == 'D' || correctOptStr == '3') correctIdx = 3;

      final explanation = row.length > 9 ? row[9].toString().trim() : '';
      final difficulty = row.length > 10 ? row[10].toString().trim().toLowerCase() : 'easy';

      list.add(AptitudeProblemModel(
        id: 'ap_csv_${DateTime.now().millisecondsSinceEpoch}_$i',
        category: category.isNotEmpty ? category : 'quantitative',
        year: year,
        company: company.isNotEmpty ? company : 'TCS',
        questionText: questionText,
        options: [optionA, optionB, optionC, optionD],
        correctOptionIndex: correctIdx,
        explanation: explanation,
        difficulty: difficulty.isNotEmpty ? difficulty : 'easy',
      ));
    }
    return list;
  }

  /// Deletes all questions (Admin action).
  Future<void> deleteAllQuestions() async {
    state = state.copyWith(isLoading: true, statusMessage: "Deleting all aptitude questions...");
    try {
      final repo = ref.read(aptitudeRepositoryProvider);
      await repo.deleteAllQuestions();
      await refreshStats();
      state = state.copyWith(
        isLoading: false,
        statusMessage: "All aptitude questions deleted from Firestore.",
      );
    } catch (e) {
      state = state.copyWith(isLoading: false, statusMessage: "Error deleting questions: $e");
    }
  }
}

final adminImporterProvider =
    NotifierProvider<AdminImporterNotifier, AdminImporterState>(() {
  return AdminImporterNotifier();
});
